name: Build Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Code
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        
    - name: Install Packages
      run: flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --debug
      
    - name: Upload APK File
      uses: actions/upload-artifact@v3
      with:
        name: nfc-workout-app
        path: build/app/outputs/flutter-apk/app-debug.apk
